"use client";
import { useState } from "react";
import { Check, CheckCheck, CreditCard, Plus, RefreshCw, Settings2, Trash2 } from "lucide-react";
import { defaultPhases, phaseAmounts, phasePlanSchema } from "@/lib/payment-plan";
import { toast } from "sonner";

type Row = Record<string, any>;
const euro = (v: number) => new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR" }).format(v / 100);
const labels: Record<string, string> = { pending: "In uitvoering", submitted: "Wacht op akkoord", approved: "Goedgekeurd", paid: "Betaald", open: "Betaling open", canceled: "Geannuleerd", expired: "Verlopen", failed: "Mislukt", authorized: "Geautoriseerd" };
export default function PhasePayments({ detail, enabled, mutate, refresh, busy }: {
  detail: Row; enabled: boolean; mutate: (body: Row) => Promise<Row>; refresh: () => Promise<void>; busy: boolean;
}) {
  const [editing, setEditing] = useState(false), [schedule, setSchedule] = useState(detail.project.payment_schedule || "full");
  const [phases, setPhases] = useState<{ name: string; percentage: number }[]>(detail.phases?.length ? detail.phases : defaultPhases);
  const [working, setWorking] = useState(false);
  const p = detail.project, payments: Row[] = detail.payments || [], rows: Row[] = detail.phases || [];
  const paid = payments.filter(pay => pay.status === "paid").reduce((v, pay) => v + pay.amount, 0);
  const act = async (body: Row, checkout = false) => { if (working || busy) return false; setWorking(true); try { const result = await mutate({ ...body, project: p.id }); if (checkout) window.location.assign(result.checkout); else { await refresh(); toast.success("Bijgewerkt"); } return true; } catch (e) { toast.error((e as Error).message); return false; } finally { setWorking(false); } };
  if (p.payment_mode === "direct") return <div className="phase-payment-direct"><CreditCard size={19} /><div><b>Eigen klantfacturatie</b><p>De afrekening wordt rechtstreeks door de beheerder verzorgd.</p></div></div>;
  return <section className="phase-payments">
    <div className="phase-payment-heading"><div><h3>{p.payment_schedule === "phases" ? "Betaalplan per fase" : "Projectbetaling"}</h3><p>{euro(p.budget)} totaal · {euro(paid)} ontvangen</p></div><div>{detail.owner && payments.length === 0 && <button className="text-button" onClick={() => setEditing(!editing)}><Settings2 size={15} />{editing ? "Sluiten" : "Betaalplan"}</button>}{payments.some(pay => ["open", "pending", "authorized"].includes(pay.status)) && <button className="icon-button" disabled={working || busy} title="Betaalstatus vernieuwen" aria-label="Betaalstatus vernieuwen" onClick={() => act({ op: "paymentStatus" })}><RefreshCw size={16} /></button>}</div></div>
    {editing && <div className="phase-plan-editor"><label className="field"><span>Betaalwijze</span><select value={schedule} onChange={e => setSchedule(e.target.value)}><option value="full">Eén projectbetaling</option><option value="phases">Betalen per fase</option></select></label>{schedule === "phases" && <>{phases.map((phase, i) => <div className="phase-plan-row" key={i}><input aria-label={`Naam fase ${i + 1}`} maxLength={100} value={phase.name} onChange={e => setPhases(phases.map((v, j) => i === j ? { ...v, name: e.target.value } : v))} /><label><input type="number" min={1} max={100} aria-label={`Percentage fase ${i + 1}`} value={phase.percentage} onChange={e => setPhases(phases.map((v, j) => i === j ? { ...v, percentage: Number(e.target.value) } : v))} />%</label><button className="icon-button" disabled={phases.length <= 2} aria-label={`Fase ${i + 1} verwijderen`} onClick={() => setPhases(phases.filter((_, j) => j !== i))}><Trash2 size={14} /></button></div>)}<div className="between"><button className="text-button" disabled={phases.length >= 8} onClick={() => setPhases([...phases, { name: "Nieuwe fase", percentage: 10 }])}><Plus size={15} />Fase toevoegen</button><b>Totaal {phases.reduce((v, p) => v + p.percentage, 0)}%</b></div></>}<button className="primary" disabled={working} onClick={() => { if (schedule === "phases" && !phasePlanSchema.safeParse(phases).success) { toast.error("Vul de fasenamen in en verdeel samen precies 100%."); return; } void act({ op: "paymentPlan", schedule, phases }).then(saved => { if (saved) setEditing(false); }); }}><Check size={16} />Betaalplan vastleggen</button></div>}
    {p.payment_schedule === "phases" ? <div className="payment-phase-list">{rows.map((phase, i) => {
      const payment = payments.find(pay => pay.phase === phase.id && pay.status === "paid") || payments.find(pay => pay.phase === phase.id);
      const paid = payment?.status === "paid", active = payment && ["open", "pending", "authorized"].includes(payment.status);
      return <article className={`payment-phase ${paid ? "paid" : phase.status}`} key={phase.id}><span className="phase-number">{paid ? <Check size={17} /> : String(i + 1).padStart(2, "0")}</span><div><h4>{phase.name}</h4><small>{phase.percentage}% · {labels[paid ? "paid" : active ? payment.status : phase.status]}</small></div><strong>{euro(phase.amount)}</strong><div className="payment-phase-actions">
        {!paid && !active && phase.status === "pending" && (detail.executor || detail.owner) && <button className="outline" disabled={working || busy || !p.executor} onClick={() => act({ op: "phaseStatus", phase: phase.id, status: "submitted" })}>Aanbieden voor akkoord</button>}
        {!paid && !active && phase.status === "submitted" && detail.owner && <><button className="text-button" disabled={working || busy} onClick={() => act({ op: "phaseStatus", phase: phase.id, status: "pending" })}>Terug naar uitvoering</button><button className="outline" disabled={working || busy} onClick={() => act({ op: "phaseStatus", phase: phase.id, status: "approved" })}><CheckCheck size={15} />Goedkeuren</button></>}
        {!paid && (phase.status === "approved" || active) && detail.owner && <button className="primary" disabled={working || busy || !enabled || !detail.merchantConnected} onClick={() => act({ op: "payment", phase: phase.id }, true)}><CreditCard size={15} />{active ? "Checkout openen" : "Fase betalen"}</button>}
      </div></article>;
    })}</div> : <div className="full-payment-row"><span><CreditCard size={20} /><b>{euro(p.budget)}</b></span><span className="tag">{labels[detail.payment?.status] || "Nog niet betaald"}</span>{detail.owner && detail.payment?.status !== "paid" && <button className="primary" disabled={working || busy || !p.executor || !enabled || !detail.merchantConnected} onClick={() => act({ op: "payment" }, true)}>Betalen via Mollie</button>}</div>}
    {!enabled ? <p className="payment-availability">Mollie moet nog door de beheerder worden geactiveerd. Je kunt het betaalplan wel alvast vastleggen.</p> : !detail.merchantConnected && <p className="payment-availability">De uitvoerder moet zijn Mollie-account koppelen voordat een checkout kan worden gestart.</p>}
    <details className="payment-cost-details"><summary>Betaaldetails</summary><p>Bij een nieuwe platformbetaling is 5% platformvergoeding inbegrepen in het transactiebedrag. De uitvoerder ontvangt de rest, vóór de kosten van Mollie. Eerder gestarte betalingen behouden hun oorspronkelijke bedrag en vergoeding.</p>{p.payment_schedule === "phases" && <p>De fasebedragen vormen samen het projecttotaal. Betalen kan na akkoord op de betreffende fase.</p>}</details>
  </section>;
}
