"use client";
import { cloneElement, isValidElement, useId, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Check, CheckCheck, ChevronLeft, ChevronRight, Code2, Download, FileText, Globe, LayoutTemplate, Monitor, Palette, Plus, Save, Settings2, Smartphone, Sparkles, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { WebsiteConfiguration, configurationSchema, configurationDocument, configurationChecklist, featureOptions, newConfiguration, sections, SectionKind } from "@/lib/configurator";
import { defaultPhases, phaseAmounts } from "@/lib/payment-plan";

const steps = ["Briefing", "Pagina’s", "Functies", "Huisstijl", "Techniek", "Afspraken", "Documentatie"];
const euro = (v: number) => new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR" }).format(v / 100);
const pagePresets = [
  { title: "Diensten", slug: "/diensten", sections: ["hero", "services", "pricing", "cta"] as SectionKind[] },
  { title: "Portfolio", slug: "/portfolio", sections: ["hero", "portfolio", "cta"] as SectionKind[] },
  { title: "Nieuws", slug: "/nieuws", sections: ["hero", "blog", "cta"] as SectionKind[] },
  { title: "Webshop", slug: "/webshop", sections: ["hero", "products", "faq"] as SectionKind[] },
  { title: "Veelgestelde vragen", slug: "/vragen", sections: ["hero", "faq", "contact"] as SectionKind[] },
];
function downloadDocument(text: string) {
  const url = URL.createObjectURL(new Blob([text], { type: "text/markdown;charset=utf-8" }));
  const a = document.createElement("a"); a.href = url; a.download = "bouwr-projectbriefing.md"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export default function WebsiteConfigurator({ initial, projectId, admin, brandName, onDraft, onPublish, onNew }: {
  initial?: WebsiteConfiguration | null; projectId?: string; admin?: boolean; brandName?: string;
  onDraft: (c: WebsiteConfiguration) => Promise<void>; onPublish: (c: WebsiteConfiguration, projectId?: string) => Promise<void>; onNew: () => void;
}) {
  const [c, setC] = useState<WebsiteConfiguration>(() => initial || { ...newConfiguration(), brandName: brandName || "Jouw bedrijf" });
  const [step, setStep] = useState(0), [pageId, setPageId] = useState(c.pages[0].id), [mobile, setMobile] = useState(false);
  const [busy, setBusy] = useState(false), [showDocument, setShowDocument] = useState(false), [pageTitle, setPageTitle] = useState("");
  const document = useMemo(() => configurationDocument(c), [c]);
  const checkCount = useMemo(() => configurationChecklist(c).length, [c]);
  const page = c.pages.find(p => p.id === pageId) || c.pages[0];
  const update = <K extends keyof WebsiteConfiguration>(key: K, value: WebsiteConfiguration[K]) => setC(current => ({ ...current, [key]: value }));
  const updatePage = (patch: Partial<WebsiteConfiguration["pages"][number]>) => update("pages", c.pages.map(p => p.id === page.id ? { ...p, ...patch } : p));
  const toggleFeature = (id: string) => {
    let features = c.features.includes(id) ? c.features.filter(f => f !== id) : [...c.features, id];
    if (id === "catalog" && !features.includes(id)) features = features.filter(f => f !== "cart");
    if (id === "accounts" && !features.includes(id)) features = features.filter(f => f !== "client-portal");
    if (features.includes("cart") && !features.includes("catalog")) features.push("catalog");
    if (features.includes("client-portal") && !features.includes("accounts")) features.push("accounts");
    if (id === "multilingual" && !features.includes(id)) update("languages", [c.languages[0]]);
    update("features", features);
  };
  const addPage = (preset?: typeof pagePresets[number]) => {
    if (c.pages.length >= 20) return;
    const title = preset?.title || pageTitle.trim(); if (!title) return;
    const base = preset?.slug || "/" + title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    let slug = base || "/pagina", n = 2; while (c.pages.some(p => p.slug === slug)) slug = `${base}-${n++}`;
    const p = { id: crypto.randomUUID(), title, slug, sections: preset?.sections || ["hero", "features", "cta"] as SectionKind[] };
    setC(current => ({ ...current, pages: [...current.pages, p], features: [...new Set([...current.features, ...(p.sections.includes("products") ? ["catalog"] : []), ...(p.sections.includes("blog") ? ["blog"] : []), ...(p.sections.includes("portfolio") ? ["portfolio"] : [])])] }));
    setPageId(p.id); setPageTitle("");
  };
  const run = async (action: () => Promise<void>) => { if (busy) return; setBusy(true); try { await action(); } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); } };
  const valid = () => {
    const parsed = configurationSchema.safeParse(c);
    if (!parsed.success) throw Error(parsed.error.issues[0]?.message || "Controleer de gekozen opties.");
    return parsed.data;
  };
  const publish = () => run(async () => {
    const value = valid();
    if (!value.title || !value.client || value.budget < 100 || !value.deadline) { setStep(!value.title || !value.client ? 0 : 5); throw Error("Vul projectnaam, klant, budget en opleverdatum in."); }
    if (!value.purpose) { setStep(0); throw Error("Beschrijf het doel van de website."); }
    if (value.paymentSchedule === "phases" && phaseAmounts(value.budget, value.phases).some(v => v < 100)) throw Error("Iedere betaalfase moet minimaal € 1 zijn.");
    await onPublish(value, projectId);
  });
  return <div className="website-configurator">
    <div className="configurator-toolbar"><div><span className="configurator-kicker"><Sparkles size={16} /> {projectId ? "Project aanpassen" : "Website samenstellen"}</span><span className="configurator-count">{c.pages.length} pagina’s · {c.features.length} functies · {checkCount} controlepunten</span></div><div className="dashboard-actions"><button className="text-button" onClick={onNew} disabled={busy}>Nieuw concept</button>{!projectId && <button className="outline" disabled={busy} onClick={() => run(async () => { await onDraft(valid()); toast.success("Concept opgeslagen"); })}><Save size={16} /> Concept opslaan</button>}<button className="primary" disabled={busy} onClick={() => step === 6 ? publish() : setStep(6)}><CheckCheck size={16} />{busy ? "Opslaan…" : step === 6 ? projectId ? "Project bijwerken" : "Opdracht plaatsen" : projectId ? "Wijzigingen bekijken" : "Briefing afronden"}</button></div></div>
    <div className="configurator-layout">
      <section className="configuration-panel">
        <nav className="configurator-steps" aria-label="Configuratiestappen">{steps.map((label, i) => <button key={label} className={step === i ? "active" : ""} aria-current={step === i ? "step" : undefined} onClick={() => setStep(i)}><span>{i + 1}</span>{label}</button>)}</nav>
        <div className="configuration-fields">
          <div className="configuration-step-heading"><span>STAP {step + 1} VAN {steps.length}</span><h2>{["Waar bouwen we aan?", "De structuur van je website", "Wat moet de website kunnen?", "Geef je website karakter", "Een stevig technisch fundament", "Heldere afspraken vooraf", "Van keuzes naar een opdracht"][step]}</h2><p>{["Leg het doel en de doelgroep vast. Dit vormt de basis voor de briefing.", "Kies pagina’s en bepaal de secties. Het voorbeeld volgt je keuzes.", "Selecteer de functies die binnen de opdracht vallen.", "Bekijk direct hoe kleuren, tekst en stijl samenkomen.", "Kies het beheer, de koppelingen en de eisen voor oplevering.", "Stem planning, samenwerking en betaling af.", "Controleer de gegenereerde briefing voordat je de opdracht plaatst."][step]}</p></div>
          {step === 0 && <>
            <ConfigField label="Projectnaam"><input maxLength={180} value={c.title} placeholder="Bijvoorbeeld: Website voor Studio Noord" onChange={e => update("title", e.target.value)} /></ConfigField>
            <ConfigField label="Klant / organisatie" hint="De klantnaam blijft afgeschermd voor andere bieders."><input maxLength={180} value={c.client} onChange={e => update("client", e.target.value)} /></ConfigField>
            <ConfigField label="Wat wil je met de website bereiken?" hint="Dit doel komt ook in de openbare omschrijving. Plaats hier geen vertrouwelijke gegevens."><textarea rows={4} maxLength={1600} value={c.purpose} placeholder="Meer offerteaanvragen, een beter portfolio, online verkoop…" onChange={e => update("purpose", e.target.value)} /></ConfigField>
            <ConfigField label="Voor wie is de website?"><textarea rows={3} maxLength={800} value={c.audience} placeholder="Doelgroep, behoeften en belangrijkste bezoekersactie" onChange={e => update("audience", e.target.value)} /></ConfigField>
            <ConfigField label="Type project"><div className="config-type-options">{["Website", "WordPress", "Shopify", "Webapp"].map(category => <button key={category} className={c.category === category ? "selected" : ""} onClick={() => setC(current => ({ ...current, category: category as WebsiteConfiguration["category"], cms: category === "WordPress" ? "WordPress / ACF" : category === "Shopify" ? "Shopify" : category === "Webapp" ? "Eigen CMS" : "Geen CMS", features: category === "Shopify" ? [...new Set([...current.features, "catalog", "cart", "payments", "shipping"])] : current.features }))}><Code2 size={19} />{category}{c.category === category && <Check size={15} />}</button>)}</div></ConfigField>
          </>}
          {step === 1 && <>
            <div className="config-page-list">{c.pages.map((p, i) => <div key={p.id} className={page.id === p.id ? "selected" : ""}><button className="config-page-main" onClick={() => setPageId(p.id)}><LayoutTemplate size={17} /><span><b>{p.title}</b><small>{p.slug}</small></span></button><button className="icon-button" disabled={i === 0} aria-label={`${p.title} omhoog`} onClick={() => { const next = [...c.pages]; [next[i - 1], next[i]] = [next[i], next[i - 1]]; update("pages", next); }}><ArrowUp size={14} /></button><button className="icon-button" disabled={i === c.pages.length - 1} aria-label={`${p.title} omlaag`} onClick={() => { const next = [...c.pages]; [next[i + 1], next[i]] = [next[i], next[i + 1]]; update("pages", next); }}><ArrowDown size={14} /></button><button className="icon-button danger" disabled={p.slug === "/"} aria-label={`${p.title} verwijderen`} onClick={() => { update("pages", c.pages.filter(item => item.id !== p.id)); if (page.id === p.id) setPageId(c.pages[0].id); }}><Trash2 size={15} /></button></div>)}</div>
            <div className="config-add-page"><input aria-label="Naam nieuwe pagina" maxLength={80} value={pageTitle} placeholder="Eigen pagina toevoegen" onChange={e => setPageTitle(e.target.value)} onKeyDown={e => { if (e.key === "Enter") addPage(); }} /><button className="outline" disabled={!pageTitle.trim() || c.pages.length >= 20} onClick={() => addPage()}><Plus size={16} /> Toevoegen</button></div>
            <div className="config-page-presets">{pagePresets.filter(p => !c.pages.some(page => page.slug === p.slug)).map(p => <button key={p.slug} disabled={c.pages.length >= 20} onClick={() => addPage(p)}><Plus size={13} />{p.title}</button>)}</div>
            <div className="config-page-editor"><h3>{page.title} instellen</h3><div className="form-grid"><ConfigField label="Paginanaam"><input value={page.title} maxLength={80} onChange={e => updatePage({ title: e.target.value })} /></ConfigField><ConfigField label="Pagina-adres"><input value={page.slug} readOnly={page.slug === "/"} maxLength={100} onChange={e => updatePage({ slug: e.target.value })} /></ConfigField></div>
              <h4>Secties op deze pagina</h4><div className="config-section-order">{page.sections.map((s, i) => <div key={s}><span>{String(i + 1).padStart(2, "0")}</span><b>{sections[s]}</b><button className="icon-button" disabled={i === 0} aria-label={`${sections[s]} omhoog`} onClick={() => { const next = [...page.sections]; [next[i - 1], next[i]] = [next[i], next[i - 1]]; updatePage({ sections: next }); }}><ArrowUp size={14} /></button><button className="icon-button" disabled={i === page.sections.length - 1} aria-label={`${sections[s]} omlaag`} onClick={() => { const next = [...page.sections]; [next[i + 1], next[i]] = [next[i], next[i + 1]]; updatePage({ sections: next }); }}><ArrowDown size={14} /></button><button className="icon-button" disabled={page.sections.length === 1} aria-label={`${sections[s]} verwijderen`} onClick={() => updatePage({ sections: page.sections.filter(item => item !== s) })}><Trash2 size={14} /></button></div>)}</div>
              <div className="config-section-choices">{Object.entries(sections).filter(([s]) => !page.sections.includes(s as SectionKind)).map(([s, label]) => <button key={s} onClick={() => updatePage({ sections: [...page.sections, s as SectionKind] })}><Plus size={13} />{label}</button>)}</div>
            </div>
          </>}
          {step === 2 && <>{[...new Set(featureOptions.map(f => f.group))].map(group => <div className="config-feature-group" key={group}><h3>{group}</h3>{featureOptions.filter(f => f.group === group).map(f => <label key={f.id} className={`config-feature ${c.features.includes(f.id) ? "selected" : ""}`}><input type="checkbox" checked={c.features.includes(f.id)} onChange={() => toggleFeature(f.id)} /><span><b>{f.label}</b><small>{f.detail}</small></span></label>)}</div>)}
            <h3>Talen</h3><div className="config-checkbox-grid">{["Nederlands", "Engels", "Duits", "Frans"].map(language => <label key={language}><input type="checkbox" checked={c.languages.includes(language as any)} disabled={c.languages.length === 1 && c.languages.includes(language as any)} onChange={() => { const languages = c.languages.includes(language as any) ? c.languages.filter(l => l !== language) : [...c.languages, language as any]; setC(current => ({ ...current, languages, features: languages.length > 1 ? [...new Set([...current.features, "multilingual"])] : current.features })); }} />{language}</label>)}</div>
          </>}
          {step === 3 && <>
            <ConfigField label="Merknaam"><input maxLength={100} value={c.brandName} onChange={e => update("brandName", e.target.value)} /></ConfigField>
            <ConfigField label="Stijl"><div className="config-style-options">{[{ id: "minimal", name: "Rustig", text: "Licht, helder en ruim" }, { id: "editorial", name: "Verhalend", text: "Typografie en inhoud" }, { id: "bold", name: "Krachtig", text: "Contrast en uitgesproken koppen" }].map(style => <button key={style.id} className={`style-${style.id} ${c.style === style.id ? "selected" : ""}`} onClick={() => update("style", style.id as WebsiteConfiguration["style"])}><span>Aa<span /></span><b>{style.name}</b><small>{style.text}</small></button>)}</div></ConfigField>
            <div className="form-grid"><ConfigField label="Accentkleur"><div className="config-color"><input type="color" value={c.primaryColor} onChange={e => update("primaryColor", e.target.value)} /><code>{c.primaryColor}</code></div></ConfigField><ConfigField label="Donkere kleur"><div className="config-color"><input type="color" value={c.secondaryColor} onChange={e => update("secondaryColor", e.target.value)} /><code>{c.secondaryColor}</code></div></ConfigField></div>
            <div className="form-grid"><ConfigField label="Typografie"><select value={c.typography} onChange={e => update("typography", e.target.value as any)}><option value="sans">Sans-serif · modern</option><option value="serif">Serif koppen · redactioneel</option></select></ConfigField><ConfigField label="Hoeken"><select value={c.corners} onChange={e => update("corners", e.target.value as any)}><option value="soft">Afgerond</option><option value="square">Recht</option></select></ConfigField></div>
            <ConfigField label="Hoofdkop"><input maxLength={140} value={c.headline} onChange={e => update("headline", e.target.value)} /></ConfigField>
            <ConfigField label="Introductie"><textarea maxLength={400} rows={3} value={c.intro} onChange={e => update("intro", e.target.value)} /></ConfigField>
            <ConfigField label="Tekst van de hoofdknop"><input maxLength={50} value={c.actionLabel} onChange={e => update("actionLabel", e.target.value)} /></ConfigField>
            <ConfigField label="Wie verzorgt de content?"><select value={c.contentBy} onChange={e => update("contentBy", e.target.value as any)}>{["Klant levert aan", "Developer verzorgt", "Samen"].map(v => <option key={v}>{v}</option>)}</select></ConfigField>
            <h3>Wat is al beschikbaar?</h3><div className="config-checkbox-grid">{["Logo", "Kleuren", "Lettertypen", "Teksten", "Fotografie", "Productgegevens"].map(asset => <label key={asset}><input type="checkbox" checked={c.assets.includes(asset as any)} onChange={() => update("assets", c.assets.includes(asset as any) ? c.assets.filter(a => a !== asset) : [...c.assets, asset as any])} />{asset}</label>)}</div><p className="config-hint">Voeg de echte merkbestanden na het plaatsen toe in de projectmap Huisstijl.</p>
          </>}
          {step === 4 && <>
            <ConfigField label="Contentbeheer"><select value={c.cms} onChange={e => update("cms", e.target.value as any)}>{["WordPress / ACF", "Shopify", "Eigen CMS", "Geen CMS"].map(v => <option key={v}>{v}</option>)}</select></ConfigField>
            <ConfigField label="Koppelingen" hint="Noem systemen, gegevens en de gewenste richting. Bewaar tokens later in de hostingkluis."><textarea rows={4} maxLength={1500} value={c.integrations} placeholder="Bijvoorbeeld: offerteaanvragen naar HubSpot, nieuwsbrief naar Mailchimp" onChange={e => update("integrations", e.target.value)} /></ConfigField>
            <ConfigField label="SEO"><select value={c.seo} onChange={e => update("seo", e.target.value as any)}>{["Technische basis", "Basis + zoekwoordstructuur", "Uitgebreide SEO"].map(v => <option key={v}>{v}</option>)}</select></ConfigField>
            <ConfigField label="Toegankelijkheid"><select value={c.accessibility} onChange={e => update("accessibility", e.target.value as any)}><option>WCAG 2.2 AA als doel</option><option>WCAG 2.2 AA + audit</option></select></ConfigField>
            <ConfigField label="Performance"><select value={c.performance} onChange={e => update("performance", e.target.value as any)}><option>Geoptimaliseerd responsive</option><option>Core Web Vitals als acceptatiepunt</option></select></ConfigField>
            <ConfigField label="Technische afspraken"><textarea rows={4} maxLength={2000} value={c.technicalNotes} placeholder="Stack, infrastructuur, API’s, bestaande omgeving of bijzondere eisen" onChange={e => update("technicalNotes", e.target.value)} /></ConfigField>
            <div className="config-quality-note"><CheckCheck size={20} /><p>Responsive gedrag, veilige verwerking, browsercontrole, back-ups en overdracht komen standaard in de opleverchecklist.</p></div>
          </>}
          {step === 5 && <>
            <div className="form-grid"><ConfigField label="Indicatief budget (€)"><input type="number" min={1} max={1000000} step="0.01" value={c.budget ? c.budget / 100 : ""} onChange={e => update("budget", Math.round(Number(e.target.value) * 100))} /></ConfigField><ConfigField label="Gewenste opleverdatum"><input type="date" value={c.deadline} onChange={e => update("deadline", e.target.value)} /></ConfigField></div>
            <ConfigField label="Wie beheert de hosting?"><select value={c.hosting} onChange={e => update("hosting", e.target.value as any)}><option>Eigen hosting</option><option>Hosting uitvoerder</option></select></ConfigField>
            <label className="config-toggle"><input type="checkbox" checked={c.contact} onChange={e => update("contact", e.target.checked)} /><span><b>Uitvoerder mag contact hebben met de klant</b><small>Het klantgesprek is apart van de interne developerberichten.</small></span></label>
            {admin && <label className="config-toggle"><input type="checkbox" checked={c.paymentMode === "direct"} onChange={e => update("paymentMode", e.target.checked ? "direct" : "platform")} /><span><b>Eigen klantfacturatie</b><small>Je regelt de afrekening zelf met je klant.</small></span></label>}
            {c.paymentMode === "platform" && <><ConfigField label="Betaalmomenten"><div className="config-radio-options">{[{ id: "full", label: "Eén projectbetaling", hint: "Het afgesproken totaal in één keer" }, { id: "phases", label: "Betalen per fase", hint: "Een betaling na akkoord op elke fase" }].map(v => <label key={v.id} className={c.paymentSchedule === v.id ? "selected" : ""}><input type="radio" name="schedule" checked={c.paymentSchedule === v.id} onChange={() => update("paymentSchedule", v.id as any)} /><span><b>{v.label}</b><small>{v.hint}</small></span></label>)}</div></ConfigField>
              {c.paymentSchedule === "phases" && <div className="config-phases">{c.phases.map((phase, i) => <div key={i}><input aria-label={`Naam fase ${i + 1}`} maxLength={100} value={phase.name} onChange={e => update("phases", c.phases.map((p, j) => i === j ? { ...p, name: e.target.value } : p))} /><label><input aria-label={`Percentage fase ${i + 1}`} type="number" min={1} max={100} value={phase.percentage} onChange={e => update("phases", c.phases.map((p, j) => i === j ? { ...p, percentage: Number(e.target.value) } : p))} />%</label><small>{euro(phaseAmounts(c.budget, c.phases)[i])}</small><button className="icon-button" disabled={c.phases.length <= 2} aria-label={`Fase ${i + 1} verwijderen`} onClick={() => update("phases", c.phases.filter((_, j) => j !== i))}><Trash2 size={15} /></button></div>)}<div className="config-phase-total"><button className="text-button" disabled={c.phases.length >= 8} onClick={() => update("phases", [...c.phases, { name: "Nieuwe fase", percentage: 10 }])}><Plus size={15} />Fase toevoegen</button><b className={c.phases.reduce((v, p) => v + p.percentage, 0) !== 100 ? "invalid" : ""}>Totaal {c.phases.reduce((v, p) => v + p.percentage, 0)}%</b></div></div>}
            </>}
            <div className="form-grid"><ConfigField label="Revisierondes"><input type="number" min={0} max={20} value={c.revisions} onChange={e => update("revisions", Number(e.target.value))} /></ConfigField><ConfigField label="Na oplevering"><select value={c.maintenance} onChange={e => update("maintenance", e.target.value as any)}>{["Alleen overdracht", "Onderhoudsafspraak maken", "Onderhoud inbegrepen"].map(v => <option key={v}>{v}</option>)}</select></ConfigField></div>
            <ConfigField label="Wat valt buiten de opdracht?"><textarea maxLength={1500} rows={3} value={c.exclusions} placeholder="Bijvoorbeeld: fotografie, vertalingen, licenties of migratie van oude orders" onChange={e => update("exclusions", e.target.value)} /></ConfigField>
          </>}
          {step === 6 && <>
            <div className="config-final-summary"><span><CheckCheck size={22} /></span><div><h3>{c.title || "Jouw nieuwe project"}</h3><p>{c.category} · {c.pages.length} pagina’s · {c.features.length} functies</p><strong>{euro(c.budget)}</strong><small>{c.paymentMode === "direct" ? "Eigen facturatie" : c.paymentSchedule === "phases" ? `${c.phases.length} betaalfases via Mollie` : "Projectbetaling via Mollie"}</small></div></div>
            <div className="config-document-actions"><button className="outline" onClick={() => downloadDocument(document)}><Download size={16} /> Briefing downloaden</button><button className="text-button" onClick={() => setShowDocument(!showDocument)}><FileText size={16} />{showDocument ? "Briefing sluiten" : "Volledige briefing bekijken"}</button></div>
            {showDocument ? <pre className="configuration-document">{document}</pre> : <div className="config-document-sections">{["Doel & doelgroep", "Pagina’s & secties", "Functies & koppelingen", "Huisstijl & content", "Techniek & kwaliteit", "Afspraken & betaalplan", "Opleverchecklist"].map(label => <div key={label}><Check size={16} />{label}</div>)}</div>}
            <p className="config-hint">De volledige briefing blijft binnen het projectteam. In de marktplaats verschijnt een korte omschrijving van het doel, de pagina’s en functies.</p>
            {projectId && <p className="config-hint">Een gewijzigde scope vervangt de openstaande biedingen. Bieders krijgen een melding en kunnen een nieuw bod doen.</p>}
            <button className="primary config-publish" disabled={busy} onClick={publish}><CheckCheck size={18} />{busy ? "Opslaan…" : projectId ? "Project bijwerken" : "Opdracht plaatsen"}</button>
          </>}
        </div>
        <div className="config-step-footer"><button className="text-button" disabled={step === 0} onClick={() => setStep(step - 1)}><ChevronLeft size={16} /> Vorige</button><span>{step + 1} / {steps.length}</span>{step < 6 ? <button className="primary" onClick={() => setStep(step + 1)}>Volgende <ChevronRight size={16} /></button> : <button className="outline" onClick={() => setStep(0)}>Keuzes aanpassen</button>}</div>
      </section>
      <aside className="configurator-preview"><div className="preview-toolbar"><span><Globe size={16} />Visueel voorbeeld</span><div role="group" aria-label="Voorbeeldformaat"><button className={!mobile ? "selected" : ""} aria-label="Desktopvoorbeeld" aria-pressed={!mobile} onClick={() => setMobile(false)}><Monitor size={17} /></button><button className={mobile ? "selected" : ""} aria-label="Mobiel voorbeeld" aria-pressed={mobile} onClick={() => setMobile(true)}><Smartphone size={17} /></button></div></div><div className="preview-page-select"><select aria-label="Voorbeeldpagina" value={page.id} onChange={e => setPageId(e.target.value)}>{c.pages.map(p => <option key={p.id} value={p.id}>{p.title} · {p.slug}</option>)}</select><span>{page.sections.length} secties</span></div>
        <div className={`config-preview-frame ${mobile ? "is-mobile" : ""}`}><div className="config-browser-bar"><span /><span /><span /><small>{c.brandName.toLowerCase().replace(/[^a-z0-9]/g, "") || "jouwwebsite"}.nl{page.slug === "/" ? "" : page.slug}</small></div><WebsitePreview c={c} page={page} selectPage={setPageId} /></div><p className="preview-footnote">Structuur en stijl als voorbeeld. Het definitieve ontwerp wordt door de developer uitgewerkt.</p>
      </aside>
    </div>
  </div>;
}
function ConfigField({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  const id = useId();
  const control = isValidElement<{ id?: string }>(children) && typeof children.type === "string" && ["input", "select", "textarea"].includes(children.type);
  return <div className="field config-field">{control ? <label htmlFor={id}>{label}</label> : <span id={id}>{label}</span>}{control ? cloneElement(children, { id }) : <div role="group" aria-labelledby={id}>{children}</div>}{hint && <small>{hint}</small>}</div>;
}

export function WebsitePreview({ c, page = c.pages[0], selectPage }: { c: WebsiteConfiguration; page?: WebsiteConfiguration["pages"][number]; selectPage?: (id: string) => void }) {
  const goContact = () => { const contact = c.pages.find(p => p.sections.includes("contact")); if (contact) selectPage?.(contact.id); };
  return <div className={`website-preview style-${c.style} type-${c.typography} corners-${c.corners}`} style={{ "--preview-accent": c.primaryColor, "--preview-dark": c.secondaryColor } as React.CSSProperties}>
    <header className="website-preview-header"><b>{c.brandName || "Jouw bedrijf"}<span>.</span></b><nav aria-label="Voorbeeldnavigatie">{c.pages.slice(0, 5).map(p => <button key={p.id} className={page.id === p.id ? "active" : ""} onClick={() => selectPage?.(p.id)}>{p.title}</button>)}</nav>{c.features.includes("cart") && <span className="preview-cart">Tas · 0</span>}</header>
    <main>{page.sections.map(section => <section key={section} className={`website-section section-${section}`}>
      {section === "hero" && <><span className="website-eyebrow">{page.slug === "/" ? c.brandName : page.title}</span><h2>{page.slug === "/" ? c.headline : page.title}</h2><p>{c.intro}</p><button onClick={goContact}>{c.actionLabel || "Neem contact op"}</button><div className="preview-hero-meta"><span>Persoonlijk</span><span>Betrokken</span><span>Doelgericht</span></div></>}
      {section === "services" && <><PreviewHeading label="Wat we doen" title="Diensten die verder helpen." /><div className="preview-cards">{["Advies & strategie", "Ontwerp & uitvoering", "Beheer & ondersteuning"].map((v, i) => <article key={v}><span>0{i + 1}</span><h3>{v}</h3><p>Een helder aanbod, afgestemd op jouw bezoeker.</p><small>Meer informatie</small></article>)}</div></>}
      {section === "features" && <><PreviewHeading label="Waarom kiezen voor ons" title="Aandacht voor wat telt." /><div className="preview-features">{["Een duidelijke aanpak", "Korte lijnen", "Kwaliteit in elk detail"].map(v => <div key={v}><CheckCheck size={19} /><span><h3>{v}</h3><p>Een voordeel dat past bij jouw verhaal.</p></span></div>)}</div></>}
      {(section === "portfolio" || section === "gallery") && <><PreviewHeading label={section === "portfolio" ? "Ons werk" : "Een kijkje bij ons"} title={section === "portfolio" ? "Werk om te laten zien." : "Beelden vertellen het verhaal."} /><div className="preview-project-grid">{[1, 2, 3].map(i => <article key={i}><div className="preview-image-placeholder"><LayoutTemplate size={24} /><span>{section === "portfolio" ? "Projectbeeld" : "Fotografie"}</span></div><h3>{section === "portfolio" ? `Project ${i}` : `Beeld ${i}`}</h3><small>{section === "portfolio" ? "Case & resultaat" : "Bijschrift"}</small></article>)}</div></>}
      {section === "testimonials" && <div className="preview-testimonial"><span>★★★★★</span><blockquote>“Een fijne samenwerking en een resultaat waar we trots op zijn.”</blockquote><small>Voorbeeldreview · naam klant</small></div>}
      {section === "stats" && <div className="preview-stats">{[["10+", "Jaren ervaring"], ["100+", "Projecten"], ["9,5", "Waardering"]].map(([v, label]) => <div key={label}><strong>{v}</strong><span>{label}</span></div>)}</div>}
      {section === "faq" && <><PreviewHeading label="Goed om te weten" title="Veelgestelde vragen." /><div className="preview-faq">{["Hoe werken jullie?", "Wat is de doorlooptijd?", "Hoe kan ik contact opnemen?"].map(v => <details key={v}><summary>{v}<Plus size={15} /></summary><p>Hier komt het antwoord dat past bij jouw organisatie.</p></details>)}</div></>}
      {section === "contact" && <div className="preview-contact"><div><PreviewHeading label="Laten we kennismaken" title="Een goed gesprek begint hier." /><p>Vertel ons waar je naar op zoek bent.</p>{c.features.includes("maps") && <div className="preview-map"><Globe size={22} /><span>Kaart & locatie</span></div>}{c.features.includes("whatsapp") && <small>Ook bereikbaar via WhatsApp</small>}</div><div className="preview-form"><label>Naam<input disabled placeholder="Jouw naam" /></label><label>E-mailadres<input disabled placeholder="naam@bedrijf.nl" /></label><label>Bericht<textarea disabled placeholder="Waar kunnen we je mee helpen?" /></label><button disabled>Versturen</button><small>Voorbeeldformulier</small></div></div>}
      {section === "pricing" && <><PreviewHeading label="Voor ieder vraagstuk" title="Kies wat bij je past." /><div className="preview-cards">{["Basis", "Compleet", "Op maat"].map((v, i) => <article key={v}><h3>{v}</h3><strong>{i === 2 ? "Op aanvraag" : `€ ${[99, 199][i]}`}</strong><p>Een pakket met de afgesproken onderdelen.</p><button onClick={goContact}>Meer weten</button></article>)}</div></>}
      {section === "blog" && <><PreviewHeading label="Inzicht & inspiratie" title="Het laatste nieuws." /><div className="preview-cards">{["Een kijkje achter de schermen", "Nieuwe ontwikkelingen", "Praktische tips"].map(v => <article key={v}><span>ARTIKEL</span><h3>{v}</h3><p>Een korte introductie van het artikel.</p><small>Lees het verhaal</small></article>)}</div></>}
      {section === "products" && <><PreviewHeading label="De collectie" title="Vind jouw favoriet." /><div className="preview-products">{[1, 2, 3].map(i => <article key={i}><div className="preview-image-placeholder"><LayoutTemplate size={22} /><span>Productfoto</span></div><h3>Product {i}</h3><strong>€ {(i * 24.95).toFixed(2).replace(".", ",")}</strong>{c.features.includes("cart") && <button disabled>In winkelmand</button>}</article>)}</div></>}
      {section === "cta" && <div className="preview-cta"><h2>Klaar voor de volgende stap?</h2><p>{c.actionLabel ? "We denken graag met je mee." : "Neem contact met ons op."}</p><button onClick={goContact}>{c.actionLabel || "Neem contact op"}</button></div>}
    </section>)}</main><footer className="website-preview-footer"><b>{c.brandName}</b><span>Contact · Privacy · © {new Date().getFullYear()}</span>{c.languages.length > 1 && <small>{c.languages.map(l => ({ Nederlands: "NL", Engels: "EN", Duits: "DE", Frans: "FR" }[l])).join(" / ")}</small>}</footer>
    {c.features.includes("newsletter") && <div className="preview-newsletter"><span>Blijf op de hoogte</span><span>E-mailadres</span><button disabled>Aanmelden</button></div>}
  </div>;
}
function PreviewHeading({ label, title }: { label: string; title: string }) { return <div className="preview-section-heading"><small>{label}</small><h2>{title}</h2></div>; }
